name: Run Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install updated configparser
        run: pip install configparser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Exclude the problematic tabulate==0.9.0 line from requirements.txt
          grep -v '^tabulate==0\.9\.0$' requirements.txt > requirements_no_conflict.txt
          pip install --no-cache-dir numpy==1.26.4 pygeos>=0.12.0 -r requirements_no_conflict.txt

      - name: Install conflicting package separately
        run: |
          # Install tabulate without dependency resolution
          pip install --no-deps tabulate==0.9.0

      - name: Install pygeos
        run: pip install pygeos

      - name: Check Dependency Conflicts
        run: |
          python -m pip install --upgrade pip
          pip install pipdeptree
          pip install -r requirements.txt
          pipdeptree --warn fail

      - name: Run tests
        run: python -m pytest tests/ --junitxml=report.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml
